sudo: false
dist: trusty
git:
  submodules: false # doesn't need 'em for tests
language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
services:
  - redis-server
before_install:
   - git clone git://github.com/travis-perl/helpers
   - source helpers/init
   - build-perl
   - perl -V
before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
script:
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" prove -r t
after_success:
  - cover -report codecov
